### ISSUE TITLE
Registering a codec while using pgxpool 

### ISSUE THREAD

**Issue by archer-v** [twpayne/pgx-geos#1]
Thanks you for this package

Could you add a method or describe the approach how to register the codec when *pgxpool.Pool is using instead pgx.Conn

As I understand it, pgxpool  creates and store the pool of pgx.Conn internally, and I don't see the method how to get the access to the pgx.conn object to register the codec.

**Comment by twpayne** [comment]
Fixed with 70a09a3486c3ce7caf4ec277adbac0105f981c52.
