### ISSUE TITLE
Support more postgis types

### ISSUE THREAD

**Issue by ZhouXing19** [twpayne/pgx-geos#3]
Hi! Thank you for adding support for postgis type in pgx, this is super helpful!!

Currently the repo support the codec of the `geometry` type. Wondering if there is any plan to extend the support to [other postgis types](https://github.com/postgis/postgis/blob/2773d7419c4ada598847e1b5ac9b292cbd409846/libpgcommon/lwgeom_pg.c#L192-L197), such as `geography`, `box2d`?

Thanks again!

**Comment by twpayne** [comment]
At the moment there are no such plans. Of these other PostGIS types, only `box2df` has [an equivalent type in go-geos](https://pkg.go.dev/github.com/twpayne/go-geos#Box2D).

I'd happily accept high-quality contributions that add support for these types.

**Comment by twpayne** [comment]
I had a couple of spare evenings so I've added support for `box2d` and `geography` types. These are in version `v0.0.2`, which I've just tagged.

Do you need any other types supported? If not, please close this issue.

**Comment by ZhouXing19** [comment]
This is awesome, thank you so much! Closing.

**Comment by twpayne** [comment]
For info, I [asked on `postgis-devel`](https://lists.osgeo.org/pipermail/postgis-devel/2024-June/030284.html) about the remaining types. The quick tl;dr is that `box2df` and `gidx` are internal-only and never sent over the wire, so pgx-geos doesn't need to support them.

To complete pgx-geos's type support the following are needed:

* A Go-native `box3d` type.
* Go bindings for [GDAL](https://gdal.org/) to support `raster` types. Note that GDAL's API is in C++ so it's significantly more effort to provide Go bindings to it.
